[app]
# name = "cmdb"
# description = "cmdb"
# encrypt_key = "defualt app encrypt key"


[http]
# 是否开启HTTP Server, 默认会根据是否有注册得有API对象来自动开启
enable = true
# HTTP服务Host
host = "127.0.0.1"
# HTTP服务端口
port = 8010
# API接口前缀
path_prefix = "api"
# 使用的http框架, 默认会根据当前注册的API对象,自动选择合适的框架
web_framework = ""

[grpc]
# 开启GRPC服务
enable = true
# Server监听的地址
host = "127.0.0.1"
# Server监听的端口
port = 18010
# 开启recovery恢复
recovery = true
# 开启Trace
trace = true

[mongo]
endpoints = ["127.0.0.1:27017"]
#username = "admin"
#password = "123456"
database = "dev-clould-mini"
#auth_db = "admin"
#trace = true

[apidoc]
# Swagger API Doc URL路径, 默认自动生成带前缀的地址比如: /api/{service_name}/v1/apidoc
# 你也可以在这里 修改这个相对路径
base_path = ""
# swagger json api path: {base_path}{json_path}, 比如/api/{service_name}/v1/apidoc/swagger.json
json_path = "/swagger.json"
# ui path: {base_path}{ui_path}, 比如/api/{service_name}/v1/apidoc/ui.html
ui_path = "/ui.html"