[app]
  name = "mcenter"
  description = "mcenter"
  internal_address = "http://127.0.0.1:8020"
  internal_token = "hufyCWnmC1TapxC87b2W4tB5"

[http]
  # 开启GRPC服务
  enable = true
  # HTTP服务Host
  host = "127.0.0.1"
  # HTTP服务端口
  port = 8020

[datasource]
  provider = "mysql"
  host = "127.0.0.1"
  port = 3306
  database = "go17_mcenter"
  username = "root"
  password = "123456"
  debug = true
  auto_migrate = true
